
micronaut:
  application:
    name: jump-jdbc
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http(|s):\/\/localhost(.*)

jackson:
  bean-introspection-module: true

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2